#!/bin/sh

if [ x"$1" = x"sh" ]; then
  exec $@
  exit
fi

echo "Generating config"
awk -f - <<EOF > /etc/fr24feed.ini
BEGIN {
  for(k in ENVIRON)
    if(match(k, "^FR24_(.*)", kn)) {
      gsub("_", "-", kn[1]);
      print tolower(kn[1])"="ENVIRON[k];
    }
}
EOF

exec /fr24feed_amd64/fr24feed $@
